### ISSUE TITLE
BMS state of charge tracking

### ISSUE THREAD

**Issue by colescott** [formulaslug/fs-2#6]
The state of charge (or I guess discharge) should be tracked by watt-hour counting from the current sensor and stored in the internal memory of the LPC1768.

Tasks:
- [ ] Implement analog in for current sensor and validate
- [ ] Add KVStore from mbed to store configuration and SoC values
- [ ] Compute discharge rate and update SoC accordingly
- [ ] Publish SoC to CAN bus
- [ ] Reset SoC when charging (this might require smarter charging logic)
- [ ] Add a fault for low SoC
